/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-29
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>
#include <unordered_map>

using namespace std;

#define green "\u001b[32m"
#define red "\u001b[31m"
#define normal "\033[0m"

namespace config {

    struct Header {
        string typ; // #header 
        string name = "NULL"; // name
        unordered_map<string, string> configMap; // configs
        int depth = 0;
        vector<Header*> inner;
    };
    
    /* #frontscreen, map of all the things */
    static unordered_map<string, unordered_map<string, string>> configMap;
    static vector<Header*> headerMap;
}