/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-27
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>
#include <unordered_map>

using namespace std;

#define green "\u001b[32m"
#define red "\u001b[31m"
#define normal "\033[0m"

namespace config {

    static unordered_map<string, string> configMap;

    static void printConfigMap(  ) {
        for_each(configMap.begin(), configMap.end(), 
        [](const std::pair< string, string > &p){
            std::cout << green << "{ " << p.first << ": " << p.second << " }\n" << normal;
        });
    }

    // static unordered_map<
    //                     string, pair< 
    //                                 string, unordered_map< 
    //                                                     string, string 
    //                                                      > 
    //                                 > 
    //                     > 
    // config;

    // static def string getConfig( string configSearch ) {
    //     var ret = config.find( configSearch );
    //     if( ret != config.end() ) {
    //         return config[configSearch];
    //     } else {
    //         return "-1";
    //     }
    // }
}