/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

#ifndef MY_CONFIG
#define MY_CONFIG

// author: Steven Dellamore
// date: 2020-3-9
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>
#include <unordered_map>

using namespace std;

#define green "\u001b[32m"
#define red "\u001b[31m"
#define normal "\033[0m"

namespace config {

    struct FrontPage {
        string name = "NULL"; // name
        vector< pair<string, string> > configMap;
        int depth = 0;
    };

    struct Methods {
        string name = "NULL"; // name
        vector< pair<string, string> > configMap;
        int depth = 0;
        vector<Methods*> inner; // unused
        string language = "javascript";
    };
    
    struct Functions {
        string name = "NULL"; // name
        vector< pair<string, string> > configMap;
        int depth = 0;
        vector<Methods*> inner;
        string language = "javascript";
    };

    struct Classes {
        string name = "NULL"; // name
        vector< pair<string, string> > configMap;
        int depth = 0;
        vector<Functions*> inner;
        string language = "javascript";
    };

    struct varsS {
        string name = "NULL";
        string code;
        string inlinecode;
        string language = "javascript";
    };          
 
    static vector<Methods*> methods;

    static vector<Functions*> functions;

    static vector<Classes*> classes;

    static FrontPage * frontPage = new FrontPage();

    static vector<varsS*> vars;
}

#endif