/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-27
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

using namespace std;

namespace createtex {
    static void frontpage(  ) {
        {} // fix the weird syntex 
        ifstream stream( "templates/frontPage.txt" );
        string contents;
        string date = "DATE"; 
        string replaceWith = "NOTDATF"; 
        for (char ch; stream.get(ch); contents.push_back(ch)) {}
        auto pos = contents.find(date);
        while (pos != string::npos) {
            contents.replace(pos, date.length(), replaceWith);
            pos = contents.find(date, pos);
        }
        ofstream out("./output/output.tex");
        out << contents;
        out.close();
    }
}