/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-27
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>
#include <functional>

#include "config.cpp"
#include "createTex.cpp"

using namespace std;
using namespace config;
using namespace createtex;

template <typename T >
auto getNextComment( T &stream ) {
    string line;
    while (getline( stream, line )) {
        // found @TODO
        auto found = line.find("//");
        if (found != string::npos) { 
            return pair<string, int>(line, found);
        }
    }
    return pair<string, int>("-1", -1);
}

template <typename T >
auto parseLineWithComment( T line ) {
    if( line.second == -1 ) return;
    // println( "\n" + line.first.substr( line.second ) );
    istringstream lineReaderSS( line.first.substr( line.second ) );
    string word;

    auto getSubstance = [&](auto &stream) {
        string name; 
        while( word != "\\" && word != "\n" ) {
            stream >> word;
            name += word;
            name += " ";
        }
        return name.substr( 0, name.length() - 1 );
    };

    while( lineReaderSS >> word ) {
        if( word == "@author" )
            configMap["@author"] = getSubstance( lineReaderSS );
        if( word == "@date" ) 
            configMap["@date"] = getSubstance( lineReaderSS );
        if( word == "@version" ) 
            configMap["@version"] = getSubstance( lineReaderSS );
        if( word == "@company" ) 
            configMap["@company"] = getSubstance( lineReaderSS );
        if( word == "@title" ) 
            configMap["@title"] = getSubstance( lineReaderSS );
        if( word == "@location" ) 
            configMap["@location"] = getSubstance( lineReaderSS );
        if( word == "@email" ) 
            configMap["@email"] = getSubstance( lineReaderSS );
        if( word == "@frontpage" ) 
            frontpage();
    }
}

int main(int argc, char* argv[])  {
    // populateConfigMap();
    ifstream file( "input/text.cpp" );
    pair<string,int> found;
    while( found.second != -1 ) {
        found = getNextComment( file );
        parseLineWithComment( found ); 
    }
    printConfigMap();
    return 0;
}